package com.jymanager.model;

public class TMetadata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metadata.id
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metadata.title
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metadata.value
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metadata.decsription
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    private String decsription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metadata.sortorder
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    private Integer sortorder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metadata.id
     *
     * @return the value of t_metadata.id
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metadata.id
     *
     * @param id the value for t_metadata.id
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metadata.title
     *
     * @return the value of t_metadata.title
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metadata.title
     *
     * @param title the value for t_metadata.title
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metadata.value
     *
     * @return the value of t_metadata.value
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metadata.value
     *
     * @param value the value for t_metadata.value
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metadata.decsription
     *
     * @return the value of t_metadata.decsription
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public String getDecsription() {
        return decsription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metadata.decsription
     *
     * @param decsription the value for t_metadata.decsription
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public void setDecsription(String decsription) {
        this.decsription = decsription == null ? null : decsription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_metadata.sortorder
     *
     * @return the value of t_metadata.sortorder
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public Integer getSortorder() {
        return sortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_metadata.sortorder
     *
     * @param sortorder the value for t_metadata.sortorder
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    public void setSortorder(Integer sortorder) {
        this.sortorder = sortorder;
    }
}