package com.jymanager.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TYsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public TYsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andYs_idIsNull() {
            addCriterion("ys_id is null");
            return (Criteria) this;
        }

        public Criteria andYs_idIsNotNull() {
            addCriterion("ys_id is not null");
            return (Criteria) this;
        }

        public Criteria andYs_idEqualTo(String value) {
            addCriterion("ys_id =", value, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idNotEqualTo(String value) {
            addCriterion("ys_id <>", value, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idGreaterThan(String value) {
            addCriterion("ys_id >", value, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idGreaterThanOrEqualTo(String value) {
            addCriterion("ys_id >=", value, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idLessThan(String value) {
            addCriterion("ys_id <", value, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idLessThanOrEqualTo(String value) {
            addCriterion("ys_id <=", value, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idLike(String value) {
            addCriterion("ys_id like", value, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idNotLike(String value) {
            addCriterion("ys_id not like", value, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idIn(List<String> values) {
            addCriterion("ys_id in", values, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idNotIn(List<String> values) {
            addCriterion("ys_id not in", values, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idBetween(String value1, String value2) {
            addCriterion("ys_id between", value1, value2, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_idNotBetween(String value1, String value2) {
            addCriterion("ys_id not between", value1, value2, "ys_id");
            return (Criteria) this;
        }

        public Criteria andYs_typeIsNull() {
            addCriterion("ys_type is null");
            return (Criteria) this;
        }

        public Criteria andYs_typeIsNotNull() {
            addCriterion("ys_type is not null");
            return (Criteria) this;
        }

        public Criteria andYs_typeEqualTo(String value) {
            addCriterion("ys_type =", value, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeNotEqualTo(String value) {
            addCriterion("ys_type <>", value, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeGreaterThan(String value) {
            addCriterion("ys_type >", value, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeGreaterThanOrEqualTo(String value) {
            addCriterion("ys_type >=", value, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeLessThan(String value) {
            addCriterion("ys_type <", value, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeLessThanOrEqualTo(String value) {
            addCriterion("ys_type <=", value, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeLike(String value) {
            addCriterion("ys_type like", value, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeNotLike(String value) {
            addCriterion("ys_type not like", value, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeIn(List<String> values) {
            addCriterion("ys_type in", values, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeNotIn(List<String> values) {
            addCriterion("ys_type not in", values, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeBetween(String value1, String value2) {
            addCriterion("ys_type between", value1, value2, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_typeNotBetween(String value1, String value2) {
            addCriterion("ys_type not between", value1, value2, "ys_type");
            return (Criteria) this;
        }

        public Criteria andYs_nameIsNull() {
            addCriterion("ys_name is null");
            return (Criteria) this;
        }

        public Criteria andYs_nameIsNotNull() {
            addCriterion("ys_name is not null");
            return (Criteria) this;
        }

        public Criteria andYs_nameEqualTo(String value) {
            addCriterion("ys_name =", value, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameNotEqualTo(String value) {
            addCriterion("ys_name <>", value, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameGreaterThan(String value) {
            addCriterion("ys_name >", value, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameGreaterThanOrEqualTo(String value) {
            addCriterion("ys_name >=", value, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameLessThan(String value) {
            addCriterion("ys_name <", value, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameLessThanOrEqualTo(String value) {
            addCriterion("ys_name <=", value, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameLike(String value) {
            addCriterion("ys_name like", value, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameNotLike(String value) {
            addCriterion("ys_name not like", value, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameIn(List<String> values) {
            addCriterion("ys_name in", values, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameNotIn(List<String> values) {
            addCriterion("ys_name not in", values, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameBetween(String value1, String value2) {
            addCriterion("ys_name between", value1, value2, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_nameNotBetween(String value1, String value2) {
            addCriterion("ys_name not between", value1, value2, "ys_name");
            return (Criteria) this;
        }

        public Criteria andYs_subnameIsNull() {
            addCriterion("ys_subname is null");
            return (Criteria) this;
        }

        public Criteria andYs_subnameIsNotNull() {
            addCriterion("ys_subname is not null");
            return (Criteria) this;
        }

        public Criteria andYs_subnameEqualTo(String value) {
            addCriterion("ys_subname =", value, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameNotEqualTo(String value) {
            addCriterion("ys_subname <>", value, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameGreaterThan(String value) {
            addCriterion("ys_subname >", value, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameGreaterThanOrEqualTo(String value) {
            addCriterion("ys_subname >=", value, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameLessThan(String value) {
            addCriterion("ys_subname <", value, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameLessThanOrEqualTo(String value) {
            addCriterion("ys_subname <=", value, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameLike(String value) {
            addCriterion("ys_subname like", value, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameNotLike(String value) {
            addCriterion("ys_subname not like", value, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameIn(List<String> values) {
            addCriterion("ys_subname in", values, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameNotIn(List<String> values) {
            addCriterion("ys_subname not in", values, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameBetween(String value1, String value2) {
            addCriterion("ys_subname between", value1, value2, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andYs_subnameNotBetween(String value1, String value2) {
            addCriterion("ys_subname not between", value1, value2, "ys_subname");
            return (Criteria) this;
        }

        public Criteria andItem_nameIsNull() {
            addCriterion("item_name is null");
            return (Criteria) this;
        }

        public Criteria andItem_nameIsNotNull() {
            addCriterion("item_name is not null");
            return (Criteria) this;
        }

        public Criteria andItem_nameEqualTo(String value) {
            addCriterion("item_name =", value, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameNotEqualTo(String value) {
            addCriterion("item_name <>", value, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameGreaterThan(String value) {
            addCriterion("item_name >", value, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameGreaterThanOrEqualTo(String value) {
            addCriterion("item_name >=", value, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameLessThan(String value) {
            addCriterion("item_name <", value, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameLessThanOrEqualTo(String value) {
            addCriterion("item_name <=", value, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameLike(String value) {
            addCriterion("item_name like", value, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameNotLike(String value) {
            addCriterion("item_name not like", value, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameIn(List<String> values) {
            addCriterion("item_name in", values, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameNotIn(List<String> values) {
            addCriterion("item_name not in", values, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameBetween(String value1, String value2) {
            addCriterion("item_name between", value1, value2, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_nameNotBetween(String value1, String value2) {
            addCriterion("item_name not between", value1, value2, "item_name");
            return (Criteria) this;
        }

        public Criteria andItem_yearIsNull() {
            addCriterion("item_year is null");
            return (Criteria) this;
        }

        public Criteria andItem_yearIsNotNull() {
            addCriterion("item_year is not null");
            return (Criteria) this;
        }

        public Criteria andItem_yearEqualTo(String value) {
            addCriterion("item_year =", value, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearNotEqualTo(String value) {
            addCriterion("item_year <>", value, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearGreaterThan(String value) {
            addCriterion("item_year >", value, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearGreaterThanOrEqualTo(String value) {
            addCriterion("item_year >=", value, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearLessThan(String value) {
            addCriterion("item_year <", value, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearLessThanOrEqualTo(String value) {
            addCriterion("item_year <=", value, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearLike(String value) {
            addCriterion("item_year like", value, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearNotLike(String value) {
            addCriterion("item_year not like", value, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearIn(List<String> values) {
            addCriterion("item_year in", values, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearNotIn(List<String> values) {
            addCriterion("item_year not in", values, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearBetween(String value1, String value2) {
            addCriterion("item_year between", value1, value2, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_yearNotBetween(String value1, String value2) {
            addCriterion("item_year not between", value1, value2, "item_year");
            return (Criteria) this;
        }

        public Criteria andItem_typeIsNull() {
            addCriterion("item_type is null");
            return (Criteria) this;
        }

        public Criteria andItem_typeIsNotNull() {
            addCriterion("item_type is not null");
            return (Criteria) this;
        }

        public Criteria andItem_typeEqualTo(String value) {
            addCriterion("item_type =", value, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeNotEqualTo(String value) {
            addCriterion("item_type <>", value, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeGreaterThan(String value) {
            addCriterion("item_type >", value, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeGreaterThanOrEqualTo(String value) {
            addCriterion("item_type >=", value, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeLessThan(String value) {
            addCriterion("item_type <", value, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeLessThanOrEqualTo(String value) {
            addCriterion("item_type <=", value, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeLike(String value) {
            addCriterion("item_type like", value, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeNotLike(String value) {
            addCriterion("item_type not like", value, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeIn(List<String> values) {
            addCriterion("item_type in", values, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeNotIn(List<String> values) {
            addCriterion("item_type not in", values, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeBetween(String value1, String value2) {
            addCriterion("item_type between", value1, value2, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_typeNotBetween(String value1, String value2) {
            addCriterion("item_type not between", value1, value2, "item_type");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayIsNull() {
            addCriterion("item_buy_way is null");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayIsNotNull() {
            addCriterion("item_buy_way is not null");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayEqualTo(String value) {
            addCriterion("item_buy_way =", value, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayNotEqualTo(String value) {
            addCriterion("item_buy_way <>", value, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayGreaterThan(String value) {
            addCriterion("item_buy_way >", value, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayGreaterThanOrEqualTo(String value) {
            addCriterion("item_buy_way >=", value, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayLessThan(String value) {
            addCriterion("item_buy_way <", value, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayLessThanOrEqualTo(String value) {
            addCriterion("item_buy_way <=", value, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayLike(String value) {
            addCriterion("item_buy_way like", value, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayNotLike(String value) {
            addCriterion("item_buy_way not like", value, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayIn(List<String> values) {
            addCriterion("item_buy_way in", values, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayNotIn(List<String> values) {
            addCriterion("item_buy_way not in", values, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayBetween(String value1, String value2) {
            addCriterion("item_buy_way between", value1, value2, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_buy_wayNotBetween(String value1, String value2) {
            addCriterion("item_buy_way not between", value1, value2, "item_buy_way");
            return (Criteria) this;
        }

        public Criteria andItem_taxIsNull() {
            addCriterion("item_tax is null");
            return (Criteria) this;
        }

        public Criteria andItem_taxIsNotNull() {
            addCriterion("item_tax is not null");
            return (Criteria) this;
        }

        public Criteria andItem_taxEqualTo(Integer value) {
            addCriterion("item_tax =", value, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_taxNotEqualTo(Integer value) {
            addCriterion("item_tax <>", value, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_taxGreaterThan(Integer value) {
            addCriterion("item_tax >", value, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_taxGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_tax >=", value, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_taxLessThan(Integer value) {
            addCriterion("item_tax <", value, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_taxLessThanOrEqualTo(Integer value) {
            addCriterion("item_tax <=", value, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_taxIn(List<Integer> values) {
            addCriterion("item_tax in", values, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_taxNotIn(List<Integer> values) {
            addCriterion("item_tax not in", values, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_taxBetween(Integer value1, Integer value2) {
            addCriterion("item_tax between", value1, value2, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_taxNotBetween(Integer value1, Integer value2) {
            addCriterion("item_tax not between", value1, value2, "item_tax");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountIsNull() {
            addCriterion("item_cur_amount is null");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountIsNotNull() {
            addCriterion("item_cur_amount is not null");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountEqualTo(BigDecimal value) {
            addCriterion("item_cur_amount =", value, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountNotEqualTo(BigDecimal value) {
            addCriterion("item_cur_amount <>", value, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountGreaterThan(BigDecimal value) {
            addCriterion("item_cur_amount >", value, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("item_cur_amount >=", value, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountLessThan(BigDecimal value) {
            addCriterion("item_cur_amount <", value, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("item_cur_amount <=", value, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountIn(List<BigDecimal> values) {
            addCriterion("item_cur_amount in", values, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountNotIn(List<BigDecimal> values) {
            addCriterion("item_cur_amount not in", values, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("item_cur_amount between", value1, value2, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_cur_amountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("item_cur_amount not between", value1, value2, "item_cur_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountIsNull() {
            addCriterion("item_next_amount is null");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountIsNotNull() {
            addCriterion("item_next_amount is not null");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountEqualTo(BigDecimal value) {
            addCriterion("item_next_amount =", value, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountNotEqualTo(BigDecimal value) {
            addCriterion("item_next_amount <>", value, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountGreaterThan(BigDecimal value) {
            addCriterion("item_next_amount >", value, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("item_next_amount >=", value, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountLessThan(BigDecimal value) {
            addCriterion("item_next_amount <", value, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("item_next_amount <=", value, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountIn(List<BigDecimal> values) {
            addCriterion("item_next_amount in", values, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountNotIn(List<BigDecimal> values) {
            addCriterion("item_next_amount not in", values, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("item_next_amount between", value1, value2, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_next_amountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("item_next_amount not between", value1, value2, "item_next_amount");
            return (Criteria) this;
        }

        public Criteria andItem_own_userIsNull() {
            addCriterion("item_own_user is null");
            return (Criteria) this;
        }

        public Criteria andItem_own_userIsNotNull() {
            addCriterion("item_own_user is not null");
            return (Criteria) this;
        }

        public Criteria andItem_own_userEqualTo(String value) {
            addCriterion("item_own_user =", value, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userNotEqualTo(String value) {
            addCriterion("item_own_user <>", value, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userGreaterThan(String value) {
            addCriterion("item_own_user >", value, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userGreaterThanOrEqualTo(String value) {
            addCriterion("item_own_user >=", value, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userLessThan(String value) {
            addCriterion("item_own_user <", value, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userLessThanOrEqualTo(String value) {
            addCriterion("item_own_user <=", value, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userLike(String value) {
            addCriterion("item_own_user like", value, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userNotLike(String value) {
            addCriterion("item_own_user not like", value, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userIn(List<String> values) {
            addCriterion("item_own_user in", values, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userNotIn(List<String> values) {
            addCriterion("item_own_user not in", values, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userBetween(String value1, String value2) {
            addCriterion("item_own_user between", value1, value2, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_own_userNotBetween(String value1, String value2) {
            addCriterion("item_own_user not between", value1, value2, "item_own_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeIsNull() {
            addCriterion("item_input_datetime is null");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeIsNotNull() {
            addCriterion("item_input_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeEqualTo(Date value) {
            addCriterion("item_input_datetime =", value, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeNotEqualTo(Date value) {
            addCriterion("item_input_datetime <>", value, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeGreaterThan(Date value) {
            addCriterion("item_input_datetime >", value, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("item_input_datetime >=", value, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeLessThan(Date value) {
            addCriterion("item_input_datetime <", value, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("item_input_datetime <=", value, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeIn(List<Date> values) {
            addCriterion("item_input_datetime in", values, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeNotIn(List<Date> values) {
            addCriterion("item_input_datetime not in", values, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeBetween(Date value1, Date value2) {
            addCriterion("item_input_datetime between", value1, value2, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("item_input_datetime not between", value1, value2, "item_input_datetime");
            return (Criteria) this;
        }

        public Criteria andItem_input_userIsNull() {
            addCriterion("item_input_user is null");
            return (Criteria) this;
        }

        public Criteria andItem_input_userIsNotNull() {
            addCriterion("item_input_user is not null");
            return (Criteria) this;
        }

        public Criteria andItem_input_userEqualTo(String value) {
            addCriterion("item_input_user =", value, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userNotEqualTo(String value) {
            addCriterion("item_input_user <>", value, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userGreaterThan(String value) {
            addCriterion("item_input_user >", value, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userGreaterThanOrEqualTo(String value) {
            addCriterion("item_input_user >=", value, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userLessThan(String value) {
            addCriterion("item_input_user <", value, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userLessThanOrEqualTo(String value) {
            addCriterion("item_input_user <=", value, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userLike(String value) {
            addCriterion("item_input_user like", value, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userNotLike(String value) {
            addCriterion("item_input_user not like", value, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userIn(List<String> values) {
            addCriterion("item_input_user in", values, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userNotIn(List<String> values) {
            addCriterion("item_input_user not in", values, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userBetween(String value1, String value2) {
            addCriterion("item_input_user between", value1, value2, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andItem_input_userNotBetween(String value1, String value2) {
            addCriterion("item_input_user not between", value1, value2, "item_input_user");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNull() {
            addCriterion("isvalid is null");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNotNull() {
            addCriterion("isvalid is not null");
            return (Criteria) this;
        }

        public Criteria andIsvalidEqualTo(String value) {
            addCriterion("isvalid =", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotEqualTo(String value) {
            addCriterion("isvalid <>", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThan(String value) {
            addCriterion("isvalid >", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThanOrEqualTo(String value) {
            addCriterion("isvalid >=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThan(String value) {
            addCriterion("isvalid <", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThanOrEqualTo(String value) {
            addCriterion("isvalid <=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLike(String value) {
            addCriterion("isvalid like", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotLike(String value) {
            addCriterion("isvalid not like", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidIn(List<String> values) {
            addCriterion("isvalid in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotIn(List<String> values) {
            addCriterion("isvalid not in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidBetween(String value1, String value2) {
            addCriterion("isvalid between", value1, value2, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotBetween(String value1, String value2) {
            addCriterion("isvalid not between", value1, value2, "isvalid");
            return (Criteria) this;
        }

        public Criteria andCommetsIsNull() {
            addCriterion("commets is null");
            return (Criteria) this;
        }

        public Criteria andCommetsIsNotNull() {
            addCriterion("commets is not null");
            return (Criteria) this;
        }

        public Criteria andCommetsEqualTo(String value) {
            addCriterion("commets =", value, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsNotEqualTo(String value) {
            addCriterion("commets <>", value, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsGreaterThan(String value) {
            addCriterion("commets >", value, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsGreaterThanOrEqualTo(String value) {
            addCriterion("commets >=", value, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsLessThan(String value) {
            addCriterion("commets <", value, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsLessThanOrEqualTo(String value) {
            addCriterion("commets <=", value, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsLike(String value) {
            addCriterion("commets like", value, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsNotLike(String value) {
            addCriterion("commets not like", value, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsIn(List<String> values) {
            addCriterion("commets in", values, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsNotIn(List<String> values) {
            addCriterion("commets not in", values, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsBetween(String value1, String value2) {
            addCriterion("commets between", value1, value2, "commets");
            return (Criteria) this;
        }

        public Criteria andCommetsNotBetween(String value1, String value2) {
            addCriterion("commets not between", value1, value2, "commets");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ys
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}