package com.jymanager.dao;

import com.jymanager.model.TMetadata;
import com.jymanager.model.TMetadataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMetadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metadata
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    int countByExample(TMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metadata
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    int deleteByExample(TMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metadata
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    int insert(TMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metadata
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    int insertSelective(TMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metadata
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    List<TMetadata> selectByExample(TMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metadata
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") TMetadata record, @Param("example") TMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metadata
     *
     * @mbggenerated Fri May 13 16:29:56 CST 2016
     */
    int updateByExample(@Param("record") TMetadata record, @Param("example") TMetadataExample example);
}