package com.jymanager.dao;

import com.jymanager.model.TYs;
import com.jymanager.model.TYsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TYsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    int countByExample(TYsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    int deleteByExample(TYsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String ys_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    int insert(TYs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    int insertSelective(TYs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    List<TYs> selectByExample(TYsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    TYs selectByPrimaryKey(String ys_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") TYs record, @Param("example") TYsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    int updateByExample(@Param("record") TYs record, @Param("example") TYsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(TYs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Tue Jun 14 16:50:01 GMT+08:00 2016
     */
    int updateByPrimaryKey(TYs record);
}