package com.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class TYs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.id
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.ys_type
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String ysType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.ys_name
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String ysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.ys_subname
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String ysSubname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_name
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_year
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String itemYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_type
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_buy_way
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String itemBuyWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_tax
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private Integer itemTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_cur_amount
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private BigDecimal itemCurAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_next_amount
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private BigDecimal itemNextAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_own_user
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String itemOwnUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_input_datetime
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private Date itemInputDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.item_input_user
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private String itemInputUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys.isvalid
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    private Integer isvalid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.id
     *
     * @return the value of t_ys.id
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.id
     *
     * @param id the value for t_ys.id
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.ys_type
     *
     * @return the value of t_ys.ys_type
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getYsType() {
        return ysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.ys_type
     *
     * @param ysType the value for t_ys.ys_type
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setYsType(String ysType) {
        this.ysType = ysType == null ? null : ysType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.ys_name
     *
     * @return the value of t_ys.ys_name
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getYsName() {
        return ysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.ys_name
     *
     * @param ysName the value for t_ys.ys_name
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setYsName(String ysName) {
        this.ysName = ysName == null ? null : ysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.ys_subname
     *
     * @return the value of t_ys.ys_subname
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getYsSubname() {
        return ysSubname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.ys_subname
     *
     * @param ysSubname the value for t_ys.ys_subname
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setYsSubname(String ysSubname) {
        this.ysSubname = ysSubname == null ? null : ysSubname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_name
     *
     * @return the value of t_ys.item_name
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_name
     *
     * @param itemName the value for t_ys.item_name
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_year
     *
     * @return the value of t_ys.item_year
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getItemYear() {
        return itemYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_year
     *
     * @param itemYear the value for t_ys.item_year
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemYear(String itemYear) {
        this.itemYear = itemYear == null ? null : itemYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_type
     *
     * @return the value of t_ys.item_type
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_type
     *
     * @param itemType the value for t_ys.item_type
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_buy_way
     *
     * @return the value of t_ys.item_buy_way
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getItemBuyWay() {
        return itemBuyWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_buy_way
     *
     * @param itemBuyWay the value for t_ys.item_buy_way
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemBuyWay(String itemBuyWay) {
        this.itemBuyWay = itemBuyWay == null ? null : itemBuyWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_tax
     *
     * @return the value of t_ys.item_tax
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public Integer getItemTax() {
        return itemTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_tax
     *
     * @param itemTax the value for t_ys.item_tax
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemTax(Integer itemTax) {
        this.itemTax = itemTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_cur_amount
     *
     * @return the value of t_ys.item_cur_amount
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public BigDecimal getItemCurAmount() {
        return itemCurAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_cur_amount
     *
     * @param itemCurAmount the value for t_ys.item_cur_amount
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemCurAmount(BigDecimal itemCurAmount) {
        this.itemCurAmount = itemCurAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_next_amount
     *
     * @return the value of t_ys.item_next_amount
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public BigDecimal getItemNextAmount() {
        return itemNextAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_next_amount
     *
     * @param itemNextAmount the value for t_ys.item_next_amount
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemNextAmount(BigDecimal itemNextAmount) {
        this.itemNextAmount = itemNextAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_own_user
     *
     * @return the value of t_ys.item_own_user
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getItemOwnUser() {
        return itemOwnUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_own_user
     *
     * @param itemOwnUser the value for t_ys.item_own_user
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemOwnUser(String itemOwnUser) {
        this.itemOwnUser = itemOwnUser == null ? null : itemOwnUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_input_datetime
     *
     * @return the value of t_ys.item_input_datetime
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public Date getItemInputDatetime() {
        return itemInputDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_input_datetime
     *
     * @param itemInputDatetime the value for t_ys.item_input_datetime
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemInputDatetime(Date itemInputDatetime) {
        this.itemInputDatetime = itemInputDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.item_input_user
     *
     * @return the value of t_ys.item_input_user
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getItemInputUser() {
        return itemInputUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.item_input_user
     *
     * @param itemInputUser the value for t_ys.item_input_user
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setItemInputUser(String itemInputUser) {
        this.itemInputUser = itemInputUser == null ? null : itemInputUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys.isvalid
     *
     * @return the value of t_ys.isvalid
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys.isvalid
     *
     * @param isvalid the value for t_ys.isvalid
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }
}