package com.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TYsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public TYsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andYsTypeIsNull() {
            addCriterion("ys_type is null");
            return (Criteria) this;
        }

        public Criteria andYsTypeIsNotNull() {
            addCriterion("ys_type is not null");
            return (Criteria) this;
        }

        public Criteria andYsTypeEqualTo(String value) {
            addCriterion("ys_type =", value, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeNotEqualTo(String value) {
            addCriterion("ys_type <>", value, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeGreaterThan(String value) {
            addCriterion("ys_type >", value, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ys_type >=", value, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeLessThan(String value) {
            addCriterion("ys_type <", value, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeLessThanOrEqualTo(String value) {
            addCriterion("ys_type <=", value, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeLike(String value) {
            addCriterion("ys_type like", value, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeNotLike(String value) {
            addCriterion("ys_type not like", value, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeIn(List<String> values) {
            addCriterion("ys_type in", values, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeNotIn(List<String> values) {
            addCriterion("ys_type not in", values, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeBetween(String value1, String value2) {
            addCriterion("ys_type between", value1, value2, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsTypeNotBetween(String value1, String value2) {
            addCriterion("ys_type not between", value1, value2, "ysType");
            return (Criteria) this;
        }

        public Criteria andYsNameIsNull() {
            addCriterion("ys_name is null");
            return (Criteria) this;
        }

        public Criteria andYsNameIsNotNull() {
            addCriterion("ys_name is not null");
            return (Criteria) this;
        }

        public Criteria andYsNameEqualTo(String value) {
            addCriterion("ys_name =", value, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameNotEqualTo(String value) {
            addCriterion("ys_name <>", value, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameGreaterThan(String value) {
            addCriterion("ys_name >", value, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameGreaterThanOrEqualTo(String value) {
            addCriterion("ys_name >=", value, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameLessThan(String value) {
            addCriterion("ys_name <", value, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameLessThanOrEqualTo(String value) {
            addCriterion("ys_name <=", value, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameLike(String value) {
            addCriterion("ys_name like", value, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameNotLike(String value) {
            addCriterion("ys_name not like", value, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameIn(List<String> values) {
            addCriterion("ys_name in", values, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameNotIn(List<String> values) {
            addCriterion("ys_name not in", values, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameBetween(String value1, String value2) {
            addCriterion("ys_name between", value1, value2, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsNameNotBetween(String value1, String value2) {
            addCriterion("ys_name not between", value1, value2, "ysName");
            return (Criteria) this;
        }

        public Criteria andYsSubnameIsNull() {
            addCriterion("ys_subname is null");
            return (Criteria) this;
        }

        public Criteria andYsSubnameIsNotNull() {
            addCriterion("ys_subname is not null");
            return (Criteria) this;
        }

        public Criteria andYsSubnameEqualTo(String value) {
            addCriterion("ys_subname =", value, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameNotEqualTo(String value) {
            addCriterion("ys_subname <>", value, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameGreaterThan(String value) {
            addCriterion("ys_subname >", value, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameGreaterThanOrEqualTo(String value) {
            addCriterion("ys_subname >=", value, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameLessThan(String value) {
            addCriterion("ys_subname <", value, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameLessThanOrEqualTo(String value) {
            addCriterion("ys_subname <=", value, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameLike(String value) {
            addCriterion("ys_subname like", value, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameNotLike(String value) {
            addCriterion("ys_subname not like", value, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameIn(List<String> values) {
            addCriterion("ys_subname in", values, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameNotIn(List<String> values) {
            addCriterion("ys_subname not in", values, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameBetween(String value1, String value2) {
            addCriterion("ys_subname between", value1, value2, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andYsSubnameNotBetween(String value1, String value2) {
            addCriterion("ys_subname not between", value1, value2, "ysSubname");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("item_name is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("item_name is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("item_name =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("item_name <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("item_name >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("item_name >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("item_name <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("item_name <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("item_name like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("item_name not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("item_name in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("item_name not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("item_name between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("item_name not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemYearIsNull() {
            addCriterion("item_year is null");
            return (Criteria) this;
        }

        public Criteria andItemYearIsNotNull() {
            addCriterion("item_year is not null");
            return (Criteria) this;
        }

        public Criteria andItemYearEqualTo(String value) {
            addCriterion("item_year =", value, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearNotEqualTo(String value) {
            addCriterion("item_year <>", value, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearGreaterThan(String value) {
            addCriterion("item_year >", value, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearGreaterThanOrEqualTo(String value) {
            addCriterion("item_year >=", value, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearLessThan(String value) {
            addCriterion("item_year <", value, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearLessThanOrEqualTo(String value) {
            addCriterion("item_year <=", value, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearLike(String value) {
            addCriterion("item_year like", value, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearNotLike(String value) {
            addCriterion("item_year not like", value, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearIn(List<String> values) {
            addCriterion("item_year in", values, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearNotIn(List<String> values) {
            addCriterion("item_year not in", values, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearBetween(String value1, String value2) {
            addCriterion("item_year between", value1, value2, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemYearNotBetween(String value1, String value2) {
            addCriterion("item_year not between", value1, value2, "itemYear");
            return (Criteria) this;
        }

        public Criteria andItemTypeIsNull() {
            addCriterion("item_type is null");
            return (Criteria) this;
        }

        public Criteria andItemTypeIsNotNull() {
            addCriterion("item_type is not null");
            return (Criteria) this;
        }

        public Criteria andItemTypeEqualTo(String value) {
            addCriterion("item_type =", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotEqualTo(String value) {
            addCriterion("item_type <>", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeGreaterThan(String value) {
            addCriterion("item_type >", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("item_type >=", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLessThan(String value) {
            addCriterion("item_type <", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLessThanOrEqualTo(String value) {
            addCriterion("item_type <=", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLike(String value) {
            addCriterion("item_type like", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotLike(String value) {
            addCriterion("item_type not like", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeIn(List<String> values) {
            addCriterion("item_type in", values, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotIn(List<String> values) {
            addCriterion("item_type not in", values, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeBetween(String value1, String value2) {
            addCriterion("item_type between", value1, value2, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotBetween(String value1, String value2) {
            addCriterion("item_type not between", value1, value2, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayIsNull() {
            addCriterion("item_buy_way is null");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayIsNotNull() {
            addCriterion("item_buy_way is not null");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayEqualTo(String value) {
            addCriterion("item_buy_way =", value, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayNotEqualTo(String value) {
            addCriterion("item_buy_way <>", value, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayGreaterThan(String value) {
            addCriterion("item_buy_way >", value, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayGreaterThanOrEqualTo(String value) {
            addCriterion("item_buy_way >=", value, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayLessThan(String value) {
            addCriterion("item_buy_way <", value, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayLessThanOrEqualTo(String value) {
            addCriterion("item_buy_way <=", value, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayLike(String value) {
            addCriterion("item_buy_way like", value, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayNotLike(String value) {
            addCriterion("item_buy_way not like", value, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayIn(List<String> values) {
            addCriterion("item_buy_way in", values, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayNotIn(List<String> values) {
            addCriterion("item_buy_way not in", values, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayBetween(String value1, String value2) {
            addCriterion("item_buy_way between", value1, value2, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemBuyWayNotBetween(String value1, String value2) {
            addCriterion("item_buy_way not between", value1, value2, "itemBuyWay");
            return (Criteria) this;
        }

        public Criteria andItemTaxIsNull() {
            addCriterion("item_tax is null");
            return (Criteria) this;
        }

        public Criteria andItemTaxIsNotNull() {
            addCriterion("item_tax is not null");
            return (Criteria) this;
        }

        public Criteria andItemTaxEqualTo(Integer value) {
            addCriterion("item_tax =", value, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemTaxNotEqualTo(Integer value) {
            addCriterion("item_tax <>", value, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemTaxGreaterThan(Integer value) {
            addCriterion("item_tax >", value, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemTaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_tax >=", value, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemTaxLessThan(Integer value) {
            addCriterion("item_tax <", value, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemTaxLessThanOrEqualTo(Integer value) {
            addCriterion("item_tax <=", value, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemTaxIn(List<Integer> values) {
            addCriterion("item_tax in", values, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemTaxNotIn(List<Integer> values) {
            addCriterion("item_tax not in", values, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemTaxBetween(Integer value1, Integer value2) {
            addCriterion("item_tax between", value1, value2, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemTaxNotBetween(Integer value1, Integer value2) {
            addCriterion("item_tax not between", value1, value2, "itemTax");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountIsNull() {
            addCriterion("item_cur_amount is null");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountIsNotNull() {
            addCriterion("item_cur_amount is not null");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountEqualTo(BigDecimal value) {
            addCriterion("item_cur_amount =", value, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountNotEqualTo(BigDecimal value) {
            addCriterion("item_cur_amount <>", value, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountGreaterThan(BigDecimal value) {
            addCriterion("item_cur_amount >", value, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("item_cur_amount >=", value, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountLessThan(BigDecimal value) {
            addCriterion("item_cur_amount <", value, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("item_cur_amount <=", value, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountIn(List<BigDecimal> values) {
            addCriterion("item_cur_amount in", values, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountNotIn(List<BigDecimal> values) {
            addCriterion("item_cur_amount not in", values, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("item_cur_amount between", value1, value2, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemCurAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("item_cur_amount not between", value1, value2, "itemCurAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountIsNull() {
            addCriterion("item_next_amount is null");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountIsNotNull() {
            addCriterion("item_next_amount is not null");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountEqualTo(BigDecimal value) {
            addCriterion("item_next_amount =", value, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountNotEqualTo(BigDecimal value) {
            addCriterion("item_next_amount <>", value, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountGreaterThan(BigDecimal value) {
            addCriterion("item_next_amount >", value, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("item_next_amount >=", value, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountLessThan(BigDecimal value) {
            addCriterion("item_next_amount <", value, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("item_next_amount <=", value, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountIn(List<BigDecimal> values) {
            addCriterion("item_next_amount in", values, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountNotIn(List<BigDecimal> values) {
            addCriterion("item_next_amount not in", values, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("item_next_amount between", value1, value2, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemNextAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("item_next_amount not between", value1, value2, "itemNextAmount");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserIsNull() {
            addCriterion("item_own_user is null");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserIsNotNull() {
            addCriterion("item_own_user is not null");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserEqualTo(String value) {
            addCriterion("item_own_user =", value, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserNotEqualTo(String value) {
            addCriterion("item_own_user <>", value, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserGreaterThan(String value) {
            addCriterion("item_own_user >", value, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserGreaterThanOrEqualTo(String value) {
            addCriterion("item_own_user >=", value, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserLessThan(String value) {
            addCriterion("item_own_user <", value, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserLessThanOrEqualTo(String value) {
            addCriterion("item_own_user <=", value, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserLike(String value) {
            addCriterion("item_own_user like", value, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserNotLike(String value) {
            addCriterion("item_own_user not like", value, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserIn(List<String> values) {
            addCriterion("item_own_user in", values, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserNotIn(List<String> values) {
            addCriterion("item_own_user not in", values, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserBetween(String value1, String value2) {
            addCriterion("item_own_user between", value1, value2, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemOwnUserNotBetween(String value1, String value2) {
            addCriterion("item_own_user not between", value1, value2, "itemOwnUser");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeIsNull() {
            addCriterion("item_input_datetime is null");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeIsNotNull() {
            addCriterion("item_input_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeEqualTo(Date value) {
            addCriterion("item_input_datetime =", value, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeNotEqualTo(Date value) {
            addCriterion("item_input_datetime <>", value, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeGreaterThan(Date value) {
            addCriterion("item_input_datetime >", value, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("item_input_datetime >=", value, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeLessThan(Date value) {
            addCriterion("item_input_datetime <", value, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("item_input_datetime <=", value, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeIn(List<Date> values) {
            addCriterion("item_input_datetime in", values, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeNotIn(List<Date> values) {
            addCriterion("item_input_datetime not in", values, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeBetween(Date value1, Date value2) {
            addCriterion("item_input_datetime between", value1, value2, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("item_input_datetime not between", value1, value2, "itemInputDatetime");
            return (Criteria) this;
        }

        public Criteria andItemInputUserIsNull() {
            addCriterion("item_input_user is null");
            return (Criteria) this;
        }

        public Criteria andItemInputUserIsNotNull() {
            addCriterion("item_input_user is not null");
            return (Criteria) this;
        }

        public Criteria andItemInputUserEqualTo(String value) {
            addCriterion("item_input_user =", value, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserNotEqualTo(String value) {
            addCriterion("item_input_user <>", value, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserGreaterThan(String value) {
            addCriterion("item_input_user >", value, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserGreaterThanOrEqualTo(String value) {
            addCriterion("item_input_user >=", value, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserLessThan(String value) {
            addCriterion("item_input_user <", value, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserLessThanOrEqualTo(String value) {
            addCriterion("item_input_user <=", value, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserLike(String value) {
            addCriterion("item_input_user like", value, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserNotLike(String value) {
            addCriterion("item_input_user not like", value, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserIn(List<String> values) {
            addCriterion("item_input_user in", values, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserNotIn(List<String> values) {
            addCriterion("item_input_user not in", values, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserBetween(String value1, String value2) {
            addCriterion("item_input_user between", value1, value2, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andItemInputUserNotBetween(String value1, String value2) {
            addCriterion("item_input_user not between", value1, value2, "itemInputUser");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNull() {
            addCriterion("isvalid is null");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNotNull() {
            addCriterion("isvalid is not null");
            return (Criteria) this;
        }

        public Criteria andIsvalidEqualTo(Integer value) {
            addCriterion("isvalid =", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotEqualTo(Integer value) {
            addCriterion("isvalid <>", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThan(Integer value) {
            addCriterion("isvalid >", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThanOrEqualTo(Integer value) {
            addCriterion("isvalid >=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThan(Integer value) {
            addCriterion("isvalid <", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThanOrEqualTo(Integer value) {
            addCriterion("isvalid <=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidIn(List<Integer> values) {
            addCriterion("isvalid in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotIn(List<Integer> values) {
            addCriterion("isvalid not in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidBetween(Integer value1, Integer value2) {
            addCriterion("isvalid between", value1, value2, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotBetween(Integer value1, Integer value2) {
            addCriterion("isvalid not between", value1, value2, "isvalid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ys
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ys
     *
     * @mbggenerated Mon Apr 18 21:45:26 GMT+08:00 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}